---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: demo
  labels:
    app: petclinic
  annotations:
    flux.weave.works/automated: "true"
    #flux.weave.works/tag.init: regexp:^3.*
    flux.weave.works/tag.petclinic: "semver:~1.2"
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: petclinic
    spec:
      initContainers:
      - name: init
        image: alpine:3.5
        command:
        - sleep
        - "1"
      containers:
      - name: petclinic
        image: subir0071/pet-clinic:1.2.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP


        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 64Mi
