apiVersion: v1
kind: Service
metadata:
  labels:
    run: petclinic
  name: petclinic
  namespace: demo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: petclinic
  sessionAffinity: None
  type: LoadBalancer
