apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: demo
  labels:
    app: petclinic
spec:
  type: ClusterIP
  selector:
    app: petclinic
  ports:
  - name: http
    port: 9898
    protocol: TCP
    targetPort: http